<a href="https://colab.research.google.com/github/alenanovikov/CSCI360/blob/dev/CSCI360_JupyterNT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab 0

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


List 

(a)Create a Python list object and perform some basic list functions.

(b)Learn about indexing and slicing and try them on a list.

(c)Learn about list comprehension and try to create some lists using list comprehen-sion

(d)Explore functions like min(), max(), sort(), sum(), and len() to find the sum, min, max, mean, and median of the list.

In [12]:
my_list = [1, 2, 6, 86, 23]

print(my_list[4])

print(my_list[0:2])

new_list = []

for x in my_list:
  if x==2:
    new_list.append(x)

print(new_list)

print(min(my_list))

my_list.sort()

print(my_list)

print(sum(my_list))

print(my_list)

23
[1, 2]
[2]
1
[1, 2, 6, 23, 86]
118


Queue

(a)
Explore different ways to create a python queue to perform operations efficiently.

(b)
Understand what a deque is, and what additional flexibility it provides apart from
the conventional queue data structure.

(c)
Create a function to reorganize the elements of a queue. You will need to use
loops, conditional operations, push, pop, front methods in the queue. [Refer to
the jupyter-notebook]

(d)
Solve a leetcode problem : Implement stack data structure using queues.



In [9]:
'''
Ways to implement a queue in Python:
- list: enqueue() = append() and deque() = pop(); slow takes O(n) time
- deque: enqueue() = append() and deque() = popfront(); fast takes O(1) time
- queue: enqueue() = put(item) and deque() = get(); follows FIFO rule

'''

from queue import Queue

class Stack:
  q1 = Queue()
  q2 = Queue()

  # takes O(1)
  def push(self, item):
    self.q1.put(item)

  # takes O(n)
  def pop(self):
    # copy everything except the last item to q2
    for x in range(self.q1.qsize()-1):
      self.q2.put(self.q1.get())
    # get the last item
    res = self.q1.get()
    # swap the queues
    temp = self.q1
    self.q1 = self.q2
    self.q2 = temp
    return res

  def printstack(self):
    print(self.q1.queue)

stck = Stack()
stck.push(1)
stck.push(9)
stck.push(56)
stck.push(90)
stck.printstack()
print(stck.pop())
print(stck.pop())
stck.printstack()

deque([1, 9, 56, 90])
90
56
deque([1, 9])


(a)
Create a Python Dictionary to perform operations like add, modify, and delete
an item.

(b)
Learn about different methods that can be used to explore a dictionary.

(c)
Learn about looping through the dictionary, try manipulating a dictionary with
lists as it’s item value.


In [6]:
my_dict = {
    1: "Miller",
    2: "Jacobsen",
    3: "Pavlova",
    4: "Zeke"
}

# add to a dictionary
my_dict[5] = "Russeau"
print(my_dict)
del my_dict[2]
print(my_dict)

student_scores = {1001:[95, 93, 81, 90, 100], 1002:[100, 95, 89, 87, ''], 1003:[92, 91, '', 80, '']}
print(student_scores)
print(student_scores.keys())
print(student_scores[1003])
del student_scores[1001]
print(student_scores)

for k, v in student_scores.items():
  print(k, v)

{1: 'Miller', 2: 'Jacobsen', 3: 'Pavlova', 4: 'Zeke', 5: 'Russeau'}
{1: 'Miller', 3: 'Pavlova', 4: 'Zeke', 5: 'Russeau'}
{1001: [95, 93, 81, 90, 100], 1002: [100, 95, 89, 87, ''], 1003: [92, 91, '', 80, '']}
dict_keys([1001, 1002, 1003])
[92, 91, '', 80, '']
{1002: [100, 95, 89, 87, ''], 1003: [92, 91, '', 80, '']}
1002 [100, 95, 89, 87, '']
1003 [92, 91, '', 80, '']


(a)
Create a Python list object and maintain a
min heap using the heapq library.

(b)
Create a Python list object and maintain a
max heap
using the heapq library.

(c)
Use the heapq library to implement heap sort algorithm.


In [7]:
import heapq

my_list = [56, 8, 98, 45, 6, 2]
heapq.heapify(my_list);
print(my_list)
my_max_heap = [-x for x in my_list]
heapq.heapify(my_max_heap)
print(my_max_heap)

def heap_sort(lst):
  ans = []
  max_hp = [-x for x in lst]
  heapq.heapify(max_hp)

  while(len(max_hp) > 0):
    ans.append(max_hp[0]*-1)
    max_hp[0] = max_hp[-1]
    max_hp.remove(max_hp[-1])

  return ans

print(heap_sort(my_max_heap))

[2, 6, 56, 45, 8, 98]
[-98, -45, -56, -6, -8, -2]
[-2, -6, -56, -45, -8, -98]


NumPy

(a)
Create a 2-dimensional Python list object, then convert it to a Numpy array
object.

(b)
Examine the ndim, shape, size, dtype, itemsize, and data attributes of the numpy array object. Make sure you understand their functions.

(c)
Learn the dimension concept of an ndarray object by using reshape() and flatten() methods.

(d)
Understand how the slice operation works for 1-D arrays and 2-D arrays and practice by yourself.

(e)
Learn operations on ndarray by examining the argmin(), argmax(), min(), max(), mean(), sum(), std(), dot(), square(), sqrt(), abs(). exp(), sign(), and mod() methods. Make yourself comfortable with these methods.

(f)
Examine the arange(), ones(), zeros(), eye(), linspace(), and concatenate() methods. Make yourself comfortable with these methods.


In [32]:
import numpy as np

a = [[1,2,3],
     [4,5,6],
     [7,8,9]]

b = np.array(a)

# Part b

print(b)
print(b.ndim)
print(b.size)
print(b.shape)
print(b.dtype)

print(b.reshape(1, 9)) # reshapes into an array of size 9x1
print(b.ravel()) # prints out all the elements of the array

# Slicing

print(b[0:2, 1]) # second elements in the first 2 rows
print(b[1, :]) # everything in the second row

# Part e

print(np.argmax(b)) # index of max element
print(np.max(b)) # values of max element
print(np.std(b))

# Part f

print(np.zeros((2,3)))
print(np.ones((2,3)))
print(np.linspace(1, 5, 3)) # 3 evenly spaces samples
print(np.eye(3)) # matrix in echelon row form

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
9
(3, 3)
int64
[[1 2 3 4 5 6 7 8 9]]
[1 2 3 4 5 6 7 8 9]
[2 5]
[4 5 6]
8
9
2.581988897471611
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[1. 3. 5.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
